name: pmml3
channels:
  - soumith
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _tflow_select=2.3.0
  - absl-py=0.7.1
  - asn1crypto=0.24.0
  - astor=0.7.1
  - blas=1.0
  - c-ares=1.15.0
  - ca-certificates=2019.5.15
  - cctools=895
  - certifi=2019.6.16
  - cffi=1.12.3
  - chardet=3.0.4
  - clang=4.0.1
  - clang_osx-64=4.0.1
  - clangxx=4.0.1
  - clangxx_osx-64=4.0.1
  - compiler-rt=4.0.1
  - cryptography=2.7
  - freetype=2.9.1
  - gast=0.2.2
  - grpcio=1.16.1
  - h5py=2.9.0
  - hdf5=1.10.4
  - icu=58.2
  - idna=2.8
  - intel-openmp=2019.4
  - jpeg=9b
  - keras=2.2.4
  - keras-applications=1.0.8
  - keras-base=2.2.4
  - keras-preprocessing=1.1.0
  - ld64=274.2
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgfortran=3.0.1
  - libgpuarray=0.7.6
  - libiconv=1.15
  - liblapack=3.8.0
  - libpng=1.6.37
  - libprotobuf=3.8.0
  - libtiff=4.0.10
  - libxml2=2.9.9
  - libxslt=1.1.33
  - llvm=4.0.1
  - llvm-lto-tapi=4.0.1
  - lxml=4.3.4
  - markdown=3.1.1
  - markupsafe=1.1.1
  - mkl=2019.4
  - mkl-service=2.0.2
  - mkl_fft=1.0.12
  - mkl_random=1.0.2
  - mock=3.0.5
  - ncurses=6.1
  - ninja=1.9.0
  - numpy=1.16.4
  - numpy-base=1.16.4
  - olefile=0.46
  - openssl=1.1.1c
  - pillow=6.1.0
  - pip=19.1.1
  - protobuf=3.8.0
  - pycparser=2.19
  - pyopenssl=19.0.0
  - pysocks=1.7.0
  - python=3.7.3
  - pytorch=1.0.1
  - pyyaml=5.1.1
  - readline=7.0
  - requests=2.22.0
  - scipy=1.3.0
  - setuptools=41.0.1
  - six=1.12.0
  - sqlite=3.29.0
  - tensorboard=1.13.1
  - tensorflow=1.13.1
  - tensorflow-base=1.13.1
  - tensorflow-estimator=1.13.0
  - termcolor=1.1.0
  - theano=1.0.3
  - tk=8.6.8
  - urllib3=1.24.2
  - werkzeug=0.15.4
  - wheel=0.33.4
  - xz=5.2.4
  - yaml=0.1.7
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - albumentations==0.3.0
    - cycler==0.10.0
    - decorator==4.4.0
    - elementpath==1.1.8
    - image-classifiers==0.2.0
    - imageio==2.5.0
    - imgaug==0.2.6
    - joblib==0.13.2
    - kiwisolver==1.1.0
    - mako==1.0.7
    - matplotlib==3.1.1
    - networkx==2.3
    - opencv-python==4.1.0.25
    - opencv-python-headless==4.1.0.25
    - pyparsing==2.4.0
    - python-dateutil==2.8.0
    - pywavelets==1.0.3
    - scikit-image==0.15.0
    - scikit-learn==0.21.2
    - segmentation-models==0.2.1
    - sklearn==0.0
    - xmlschema==1.0.13

